on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 18
      uses: actions/setup-node@v2-beta
      with:
        node-version: '18.12.3'
      
    - name: 🔨 Build Project
      run: |
        npm install
        elm-app build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: server7.febas.net
        username: kallejop
        password: ${{ secrets.password }}
